### ISSUE TITLE
pdf generation in other dir 

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/book#228]
cd pi
make 
make pdf did not work

cd dest; mkdir bookedit; unzip -f all4pdf.epub -d ./bookedit; sed -i -e 's/..\/media/.\/media/g' ./bookedit/EPUB/nav.xhtml
Archive:  all4pdf.epub
sed: ./bookedit/EPUB/nav.xhtml: No such file or directory
make: *** [pdf] Error 1

**Comment by fugangwang** [comment]
This was caused by '-f' option as that extracts only those already existing files which in this case does not exist.
I have changed the way a little how the bookedit was handled and the working directory will be cleared every time before unzipping.
The fix for table done afterwards was assuming for working only the cloud book. But now Also now it has been generalized to be used with other files also.
Tested and the pi pdf book showing up correctly.
