### ISSUE TITLE
above, below

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/book#231]
find all occurrences of above and below that pint to images or code and replace with either nothing if logical or previous and next.

grep -R -n above chapters | fgrep .md

* [x] chapters/devops/ansible.md:198:as above.
* [x] chapters/iaas/aws/aws.md:285:As we discussed above we can access all the service and product
* [x] chapters/iaas/watson/watson.md:26:In the case above when I was trying the Watson Assistant It was not personal when I asked the Assistant's name so it can be modified to digress!
* [x] chapters/iaas/libcloud.md:180:created as instructed above to perform various services such as
* [x] chapters/msg/avro.md:110:* This above instruction is for Python2. If one is using Python3,
* [x] chapters/msg/graphql.md:1479:> Develop a cloudmesh framework that uses all clouds above while
* [x] chapters/prg/python/facedetection/facedetection.md:228:may encounter 'FAILURE' in the ping test above.
* [x] chapters/prg/python/facedetection/facedetection.md:510:The 'apply\_batch' function that we created above is given to map
* [x] chapters/prg/python/fingerprint/fingerprint.md:221:it to use the values from above.
* [x] chapters/prg/python/python-big-data.md:24:Depending on your directory organization, the above might be slightly
* [x] chapters/prg/python/python-big-data.md:27:If you go to the link to data.gov for Bloomington above, you will see
* [x] chapters/prg/python/python-big-data.md:127:functions in the `datetime` module linked above.
* [x] chapters/in/pyenv-anaconda.md:55:-   Replicate the steps above, so you can type in ENV2 and ENV3 in your
* [x] chapters/faas/openwhisk.md:33:The `wsk` command is what is known as OpenWhisk CLI, which we will show how to install in the next sections.  Note that OpenWhisk's API is RESTful and fully HTTP based. In other words, the above-mentioned `wsk action` command  is basically a HTTP request equivalent to the following:
* [x] chapters/faas/openwhisk.md:49:After authentication and authorization using the `subjects` database, the record for the action `HelloAction` is load from `whisks` database. This record contains the code, the parameters consist of default parameters merged with user parameters, as well as the resource limits, e.g. maximum memory. The `HelloAction` record in `whisk` contains its code (listed above) and no parameters as the code does not get any parameters.
* [x] chapters/faas/openwhisk.md:70:The ` Action` example is a node.js action and therefore the invoker will start a node.js container, inject our above-mentioned code to it, runs the code and gets the results, save the logs and terminates the node.js container.
* [x] chapters/faas/openwhisk.md:122:In case you have services running on any of the ports above, you can either stop the local services that are using these ports or alternatively you can modify the `docker-compose.yml` and change the source port number in the port number mapping. The latter option is, however, more tricky because you have to make sure the change does not affect the communication between the containers. For instance if you have `Apache` service running on Port 80, then open `docker-compose.yml`, search for the keyword `80:` to find the port mapping with source port of 80:
* [x] chapters/faas/openwhisk.md:177:OpenWhisk provides a command line tool called [openwhisk-cli](https://github.com/apache/incubator-openwhisk-cli) which is used for controlling the platform. As part of the `make quick-start` command that we used above for starting the platform, the account credentials will automatically be written into the configuration of the CLI. You can either install the CLI directly from the repository or install it using `linuxbrew`. Alternatively, use the binary available in this path in OpenWhisk Devtools folder:
* [x] chapters/faas/openwhisk.md:284:The result of the command above is showing that the `hello` action has been invoked twice and the `greeter` action was invoked once. You can get more information about each of the activation using the `wsk -i activation get [ACTIVATION_ID]`:
* [x] chapters/iot/tools.md:105:above them.
* [x] chapters/faq-516.md:71:above, as the images can float and below and above makes ABSOLUTELY NO
* [x] chapters/container/docker-hadoop.md:293:to the sample result above) because the input file size was small (1,000
* [x] chapters/container/docker-swarm.md:116:the swarm. The command that is printed in the output shown above can be used 
* [x] chapters/container/dockerhub.md:70:should be able to execute the above command without using sudo.
* [x] chapters/pi/case.md:84:From the above Web page we find the following information as shown in
* [x] chapters/pi/setup-multiple.md:199:The above executable will be used by cm-burn script.
* [x] chapters/pi/setup-multiple.md:219:* The instructions above needed for the Ext2fsd to reserve the Drive Letters and any raspbian image burned to SD will be auto mounted to the specific reserved drive letters. These drive letters need to be specified while using cm-burn
* [x] chapters/pi/clusters/pi-spark-orig.md:150:Repeat above steps on all worker/slave nodes
* [x] chapters/pi/clusters/pi-spark-orig.md:154:Alternative to running above steps for each worker node, you can run
* [x] chapters/pi/clusters/pi-docker.md:63:After executing the above command, we log out of the terminal restart
* [x] chapters/pi/clusters/pi-spark.md:142:Note: The above mentioned slaves are of the same names of the
* [x] chapters/pi/setup-ultimate.md:607:using Homebrew on macOS as `brew install nmap`. Usage is as above.
* [x] chapters/pi/setup-ultimate.md:775:  between the first and second with the output from the above command
* [x] chapters/pi/kubernetes/417/bin/README.md:37:The above shell scripts are common in both worker and head.
* [x] chapters/virtualmachines/qemu-kvm.md:231:read-only connection, append the above command with -readonly.
* [x] chapters/ai/ai.md:48:sign based on being above or below the median. In k-NN predictions are
* [x] chapters/linux/ssh.md:545:After above steps you should be able to connect to the server
* [x] chapters/cloud/chameleon/faq-orig.md:518:results of the above (and any evidence of nanites you find as well).
* [x] chapters/cloud/chameleon/faq-orig.md:610:Once the program is opened, click the Generate button, seen above in
* [x] chapters/cloud/chameleon/faq-orig.md:632:now follow the steps described above (starting with the line "Provide
* [x] chapters/cloud/chameleon/faq.md:173:results of the above (and any evidence of nanites you find as well).
* [x] chapters/cloud/chameleon/user-guide.md:121:The instance list page shown above has an option 'Create Snapshot' that
* [x] chapters/cloud/chameleon/user-guide.md:172:the "OpenStack REST Interfaces" section above, then use the following
* [x] chapters/cloud/chameleon/heat.md:45:with them. The templates described above are YAML files using the [Heat
* [x] chapters/cloud/chameleon/heat.md:150:floating IP attached to it (as per the visualization above) but you can
* [x] chapters/cloud/chameleon/heat.md:157:"Resources" tab you will see the resources described above (the server,
* [x] chapters/cloud/chameleon/baremetal.md:55:features of Chameleon not covered by the guides above:
* [x] chapters/cloud/virsh.md:11:read-only connection, append the above command with -readonly.
* [x] chapters/cloud/assignment/index.md:101:structure are different from instructed above.
* [x] chapters/doc/acknowledgement.md:30:things in your paper, made suggestions. So instead of the above maybe
* [x] chapters/doc/report-book-2.md:426:-   Table captions must be above the image.
* [x] chapters/doc/piazza.md:108:2.  Proceed as in \#1 above. This will create your new Piazza account
* [x] chapters/doc/piazza.md:121:    address, follow the instructions in \#3 above.
* [x] chapters/doc/piazza.md:216:The above question will simply be commented on (if at all):
* [x] chapters/doc/piazza.md:361:  discussion   Any content that deserves its separate discussion and is not covered in the above folder.
* [x] chapters/doc/writing-markdown.md:321:1.  Table captions must be above the image.
* [x] chapters/doc/writing-markdown.md:370:things in your paper, made suggestions. So instead of the above maybe
* [x] chapters/case/case.md:167:   head. Move the laser head above the cutting material, then will
* [x] chapters/icloud/course/nosql-new.md:136:MongoDB belongs to the document model described above. Within a typical
* [x] chapters/icloud/assignment/exercise7/exercise7.md:44:the **Compute PR** step in the above diagram. The code for this can be
* [x] chapters/mapreduce/hadoop-rdma.md:89:The PCI device ID of the Virtual Function is 03:00:1 in the above
* [x] chapters/mapreduce/hadoop-rdma.md:98:Please note that and are the ones you get from the outputs of above
* [x] chapters/mapreduce/amazon-emr-2.md:58:Once all the prerequisites above have been met, an EMR cluster can now
* [x] chapters/mapreduce/amazon-emr-2.md:91:page and select the key pair generated in the steps above in the
* [x] chapters/mapreduce/amazon-emr-2.md:150:above and from that menu select 'Delete'. Once all of the folders and
* [x] chapters/bigdata/applications/sport.md:46:Wins above Replacement WAR, Discussion of Calculation, Examples,
* [x] chapters/bigdata/applications/sport.md:149:-   <http://en.wikipedia.org/wiki/Wins_Above_Replacement> [@www-wiki-wins-above-replacement]
* [x] chapters/bigdata/applications/statistics.md:78:> Pick a term from above and define it while not plagiarizing. Create a pull request.
* [x] chapters/bigdata/applications/statistics.md:84:> Pick a term above and develop a python program demonstrating it and create a pull
* [x] chapters/bigdata/applications/cloud.md:170:Before too much excitement sets in, note that spinach is above clouds
* [x] chapters/deprecated/assignments.md:28:-   Conduct the entry survey after you have done the above assignments:
* [x] chapters/deprecated/assignments.md:46:Complete the above within the first week!

BELOW
grep: chapters/doc/.#report.md: No such file or directory

* [x] chapters/devops/puppet.md:86:  encryption (Refer to Puppet Master Slave Connection figure below)
* [x] chapters/iaas/azure/azure.md:162:You will see an image such as below: +@fig:registration.
* [x] chapters/iaas/aws/link-1.md:2472:* [Amazon DynamoDBManaged NoSQL Database](/dynamodb/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/link-1.md:2489:Place](/migration-hub/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/link-1.md:2493:Transport](/snowball/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/link-1.md:2523:Delivery](/codepipeline/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/link-1.md:2584:Data](/macie/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/link-1.md:2699:Service](/workspaces/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/link-1.md:2701:Browser](/appstream2/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/link.md:1301:* [Amazon DynamoDBManaged NoSQL Database](/dynamodb/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/link.md:1318:Place](/migration-hub/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/link.md:1322:Transport](/snowball/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/link.md:1352:Delivery](/codepipeline/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/link.md:1413:Data](/macie/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/link.md:1528:Service](/workspaces/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/link.md:1530:Browser](/appstream2/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/links.md:2478:* [Amazon DynamoDBManaged NoSQL Database](/dynamodb/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/links.md:2495:Place](/migration-hub/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/links.md:2499:Transport](/snowball/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/links.md:2529:Delivery](/codepipeline/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/links.md:2590:Data](/macie/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/links.md:2705:Service](/workspaces/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/links.md:2707:Browser](/appstream2/?hp=tile&so-exp=below)
* [x] chapters/iaas/aws/aws.md:14:in Figure below: +@fig:aws-products.
* [x] chapters/iaas/aws/aws.md:98:applications and solutions. The list below showcases AWS storage 
* [x] chapters/iaas/aws/aws.md:117:databases and NoSQL based databases. The list below shows the database
* [x] chapters/iaas/aws/aws.md:152:including your email address as shown in the image below: +@fig:aws-signup.
* [x] chapters/iaas/aws/aws.md:158:provided. AWS will ask for credit/debit card details as shown below: +@fig:payment-information.
* [x] chapters/iaas/aws/aws.md:173:below: +@fig:aws-console.
* [x] chapters/iaas/aws/aws.md:252:tier agreement and you will be charged for them, see picture below: +@fig:free-tier. To view all the AWS
* [x] chapters/iaas/aws/aws.md:299:page shown below: +@fig:launch-instance. Notice that the check box for "Free tier only" is
* [x] chapters/iaas/aws/aws.md:313:eligible as shown in the image below: +@fig:instance-type. Now that you have selected all
* [x] chapters/iaas/aws/aws.md:341:shown in the image below: +@fig:running-instance1. If you do not see is initially, refresh the
* [x] chapters/iaas/aws/aws.md:374:all the AWS services through simple commands. below are two example 
* [x] chapters/iaas/watson/watson.md:56:address as shown in the image below
* [x] chapters/iaas/watson/watson.md:65:shown in the image below.
* [x] chapters/iaas/libcloud.md:302:cloud providers. In the sections below more detailed steps are shown
* [x] chapters/iaas/boto.md:62:BOTO can be configured in two ways, either by using the aws configure command if you have AWS Command line interface installed or simply by manually creating and editing the `~/.aws/credentials` file to include below parameters.
* [x] chapters/prg/python/facedetection/facedetection.md:83:exist in sub directories (see below) to add modularity to your Ansible
* [x] chapters/prg/python/facedetection/facedetection.md:322:For more information, see the useful links below.
* [x] chapters/prg/python/python.md:1110:to list as shown below:
* [x] chapters/prg/python/fingerprint/fingerprint.md:421:Both approaches are implemented below. The implementations follow the
* [x] chapters/prg/python/fingerprint/fingerprint.md:480:The `mk_short_labels` helper function will be defined below.
* [x] chapters/prg/python/python-matplotlib.md:14:libraries shown below.
* [x] chapters/prg/python/python-matplotlib.md:76:following three commands below:
* [x] chapters/prg/python/python-matplotlib.md:87:is defined in the initial plt.plot(x,y) instance, below is an example.
* [x] chapters/prg/python/python-matplotlib.md:124:An example of a bar chart is preceded below using data from
* [x] chapters/prg/python/python-matplotlib.md:154:An example of using a predefined style is shown below.
* [x] chapters/prg/python/python-editor.md:36:Once umake command is run, use below command to install Pycharm community edition:
* [x] chapters/prg/python/python-big-data.md:217:please take a look at the tutorials below. The `numpy` and `pandas`
* [x] chapters/prg/python/random-forest/random-forest.md:374:the white wine quality *data citric* acid samples is shown below. You 
* [x] chapters/prg/python/random-forest/random-forest.md:376:replace the DataFrame and column name below.
* [x] chapters/in/assignments.md:196:find the README.yml file in the link below and copy it into your github
* [x] chapters/in/assignments.md:442:README available below.
* [x] chapters/in/assignments.md:520:find the README.yml file in the link below and copy it into your github
* [x] chapters/in/assignments.md:880:**images** where all the images are stored like the structure below.
* [x] chapters/faas/introduction.md:23:listed below.
* [x] chapters/faas/aws-lambda.md:68:several major limits below. For a complete list of limits in AWS
* [x] chapters/iot/sensors.md:126:If using the LED's you will want the additional components listed below:
* [x] chapters/faq-516.md:70:notation.md file of the lecture notes Do not use the words below and
* [x] chapters/faq-516.md:71:above, as the images can float and below and above makes ABSOLUTELY NO
* [x] chapters/container/docker-hadoop.md:310:of input files to process is 10, see the line two below:
* [x] chapters/container/kubernetes-fs.md:41:commands on the **remote echo kubernetes machine** (all commands below
* [x] chapters/container/docker-swarm.md:38:   the swarm as workers. Choose a tab below to see how this plays out
* [x] chapters/container/docker-swarm.md:182:below the create and save the file. First log into the `master`
* [x] chapters/container/docker-local.md:79: This should give you an output similar to below.
* [x] chapters/pi/car/car-face.md:295:Once the libraries are installed, follow below steps to check if camera
* [x] chapters/pi/car/car-face.md:480:Camera settings need to be updated in the code as per below suggestions.
* [x] chapters/pi/clusters/pi-cassandra-apache2.md:76:Before we run the shell script we will need to update some of the files contained in the git-repo that you have cloned in the previous step. The first file is the [cassandra_custom.yaml](https://github.com/cloudmesh-community/fa18-523-84/blob/master/project-code/cassandra_custom.yaml) file.  The sections listed below need to be updated with the ip addresses that you noted when setting up the Pi's.  The other settings can remain as is.  More information about configuration options can be found on the [apache cassandra site.](https://cassandra.apache.org/doc/latest/configuration/cassandra_config_file.html)
* [x] chapters/pi/clusters/pi-now.md:108:beginning the manual steps below we assume you are able to burn an image to an
* [x] chapters/pi/setup-ultimate.md:377:`raspi-config` utility can also setup a WiFi connection. The steps below
* [x] chapters/ai/ai.md:48:sign based on being above or below the median. In k-NN predictions are
* [x] chapters/ai/ai.md:84:the Tesla is given below:
* [x] chapters/ai/ai.md:199:will import the necessary libraries shown below.
* [x] chapters/ai/ai.md:283:browser, preferably google, and following the url below the code.
* [x] chapters/ai/ai.md:335:discussion below about dynamic APIs in order to make these parameters
* [x] chapters/ai/ai.md:369:A continuous version of main.py is provided below for ease of use.
* [x] chapters/cloud/chameleon/faq-orig.md:132:below). Each Chameleon project is awarded an allocation of service units
* [x] chapters/cloud/chameleon/faq-orig.md:597:The full process can be viewed in the figure below:
* [x] chapters/cloud/chameleon/faq-orig.md:606:below.
* [x] chapters/cloud/chameleon/faq-orig.md:616:just to avoid complexity. An example is shown below. Note that the
* [x] chapters/cloud/chameleon/user-guide.md:29:below. This page provides a summary of your current and recent usage and
* [x] chapters/cloud/chameleon/user-guide.md:32:below. One thing to note is that on the left, your current project is
* [x] chapters/cloud/chameleon/user-guide.md:36:shot below, the quota and usage apply to the current project you have
* [x] chapters/cloud/chameleon/user-guide.md:46:Overview page. An example Instances page is shown below. For instances
* [x] chapters/cloud/chameleon/heat.md:99:like below: +@fig:select-template.
* [x] chapters/cloud/chameleon/heat.md:126:client instances. As below: +@fig:create-in-progress.
* [x] chapters/cloud/chameleon/heat.md:135:visualization of the deployed resources, as pictured below: +@fig:stack-visualization. The single
* [x] chapters/cloud/chameleon/heat.md:174:This template is reproduced further below, and includes inline comments
* [x] chapters/cloud/chameleon/heat.md:337:below. It is similar to the NFS share appliance, except that it deploys
* [x] chapters/cloud/chameleon/heat.md:453:customized template. The resulting topology view is shown below: +@fig:nfs-with-two-clients, as you
* [x] chapters/cloud/chameleon/heat.md:531:The image below: +@fig:outputs, shows the resulting outputs as viewed from the web
* [x] chapters/cloud/chameleon/heat.md:743:The template below illustrates how it works. It launches a group of
* [x] chapters/cloud/chameleon/start.md:78:users guides below:
* [x] chapters/cloud/chameleon/horizon.md:66:screen like the one below:
* [x] chapters/class/assignments.md:660:    below however you are free to use data from elsewhere, like scikit
* [x] chapters/class/assignments-a.md:508:    below however you are free to use data from elsewhere, like scikit
* [x] chapters/class/e222-syllabus-old.md:280:The link to the assignment in piazza is below, directions for each student will come out the week of
* [x] chapters/doc/report.md:151:13. Have you not used phrases such as shown in the Figure below, but
* [x] chapters/doc/report-2.md:190:13. Have you not used phrases such as shown in the Figure below, but
* [x] chapters/doc/report-book-2.md:312:-   Do not use phrases such as *shown in the Figure below*. Instead, use
* [x] chapters/doc/report-book-2.md:401:-   Do not artificially inflate your paper if you are below the page
* [x] chapters/doc/writing-markdown.md:306:1.  Do not artificially inflate your paper if you are below the page
* [x] chapters/doc/projects-2.md:252:    below however you are free to use data from elsewhere, like scikit
* [x] chapters/arch.md:292:The group of industry experts based use the following guiding principles to when publishing their reference Architecture (below).
* [x] chapters/icloud/project2.md:139:PageRankReduce.java. Code snapshots are shown below.
* [x] chapters/icloud/project2.md:154:below. Standard error messages such as compile errors, execution
* [x] chapters/icloud/assignment/exercise2/exercise2.md:176:PageRankReduce.java. Code snapshots are shown below.
* [x] chapters/icloud/assignment/exercise2/exercise2.md:207:Use the one-click script compileAndExecHadoopPageRank.sh provided below.
* [x] chapters/icloud/assignment/exercise3/exercise3.md:127:below.
* [x] chapters/icloud/assignment/deprecated/exercise-old7/exercise7.md:89:The two functions are listed below.
* [x] chapters/data/mongodb.md:73:To update the Ubuntu packages to the most recent versions, use below command:
* [x] chapters/mapreduce/hadoop-rdma.md:82:format - XX:XX.X) of one of the virtual functions as shown below:
* [x] chapters/mapreduce/hadoop-rdma.md:136:running the kill-vms.sh script as shown below. This script will kill all
* [x] chapters/mapreduce/hadoop-comet.md:31:detail below, with user-modified content displayed in bold. Do not alter
* [x] chapters/mapreduce/aws-emr.md:64:The EMR cluster will run on a subnet so you need to determine the appropriate subnet for you availability zone. You will need to enter your default zone in the code below.
* [x] chapters/mapreduce/amazon-emr-1.md:79:Login to AWS console, go to services and then select EMR. Click on Create Cluster. In the cluster configuration provide below details to complete to complete step execution creation.
* [x] chapters/mapreduce/amazon-emr-1.md:101:Login to AWS console, go to services and then select EMR. Click on Create Cluster. In the cluster configuration provide below details to complete.
* [x] chapters/mapreduce/amazon-emr-1.md:114:Login to AWS console, go to services and then select EMR. Click on Create Cluster. In the cluster configuration provide below details to complete.
* [x] chapters/mapreduce/amazon-emr-2.md:52:connect to the EC2 instances created by EMR [@hid-sp18-521-ec2keypair]. As the picture below: +@fig:key.
* [x] chapters/mapreduce/amazon-emr-2.md:92:drop-down menu, as below: +@fig:security. Below that you can then select which permissions model
* [x] chapters/mapreduce/mapreduce.md:119:below and both input and output here is a key/value pairs:
* [x] chapters/mapreduce/hadoop-installation.md:162:as below.
* [x] chapters/rest/rest.md:465:Your payload should look like the one below, if your output is not
* [x] chapters/rest/rest.md:466:formatted like below try adding `?pretty=1`
* [x] chapters/bigdata/applications/sport.md:169:    resources below do not exsit:
* [x] chapters/bigdata/applications/sensor.md:109:    resources below do not exsit:

**Comment by bfeng** [comment]
"above"
---

- [ ] chapters/prg/python/numpy/numpy.md:89:An operation that results in a value above that range will 'overflow'
- [ ] chapters/prg/python/python-data.md:300:It is analgous to `pprint()` function. The object created above can be viewed
- [ ] chapters/prg/python/python-data.md:344:Following code showcases usage of the above discussed attributes:
- [ ] chapters/prg/scala/scala.md:47:Now copy the line above into a teext file and name it helloworld.scala. Form the terminal
- [ ] chapters/prg/scala/scala.md:66:The code above applies the method `size` on the expression "hello!" and
- [ ] chapters/prg/scala/scala.md:112:The defintion above defines a function with three input parametes of type Double and it returns a double value.
- [ ] chapters/prg/scala/scala.md:114:We could use a block to define the body of the method above:
- [ ] chapters/prg/scala/scala.md:147:Save the above script in a file named LearnTheLanguage.scala and run
- [ ] chapters/prg/scala/scala.md:160:In the class `Person` above, we override the method toString. The method toString is
- [ ] chapters/prg/scala/scala.md:176:above we should override `equals` as follows:
- [ ] chapters/prg/scala/scala.md:205:to the members. A `private` member can be accessed only within the class. In the example above, the members
- [ ] chapters/prg/scala/scala.md:230:Note that int the code above the primary constructor of `Employee` is calling the primary constructor of its supertype.
- [ ] chapters/prg/scala/scala.md:278:The example above is an instance of an `algebraic data type`. An algebraic data type is a sealed trait together with several
- [ ] chapters/prg/scala/scala.md:349:sequential collection, it will copy all the elements in that collection to an equivalent parallel collection. So to run the above example in parallel we only need to
- [ ] chapters/in/ai-rest.md:181:above created OpenAPI specification (`gcv.yaml`) and dynamically call the method
- [ ] chapters/in/ai-rest.md:560:above created OpenAPI specification (`ai.yaml`) and dynamically call the methods
- [ ] chapters/in/aws-auroradb.md:428:> Follow the steps defined in the sections above to create an AuroraDB instance
- [ ] chapters/faas/openlambda.md:126:The above command starts running a single worker with a configuration specified in the worker.json file (described in detail later).
- [ ] chapters/faas/openlambda.md:164:In the above example, the configuration is modified so that workers will use the local registry and the "sock" sandboxing engine.
- [ ] chapters/faas/openlambda.md:190:In addition to the above commands for managing OpenLambda workers,
- [ ] chapters/faas/openlambda.md:214:The above command should use the KEY/SECRET pair used when you launched the registry earlier.
- [ ] chapters/faas/openlambda.md:272:As a developer debugging the functions, you may want to peek in the above directories to look for handler output and generated files.
- [ ] chapters/faas/openlambda.md:273:However, in order to write code for a handler that generates output in the above locations, you will need to write files to the `/host`
- [ ] chapters/iot/grovepi.md:24:be exposed to a voltage greater than a certain threshold value. Above
- [ ] chapters/faq-516.md:71:above, as the images can float and below and above makes ABSOLUTELY NO
- [ ] chapters/ai/ai.md:48:sign based on being above or below the median. In k-NN predictions are
- [ ] chapters/doc/report-book-2.md:426:-   Table captions must be above the image.
- [ ] chapters/doc/writing-markdown.md:325:1.  Table captions must be above the image.
- [ ] chapters/case/case.md:167:   head. Move the laser head above the cutting material, then will
- [ ] chapters/issues/issues.md:47:| 60 | 231 | [above, below][i231] | bfeng | internal |
- [ ] chapters/bigdata/applications/sport.md:21:sophisticated measures like Wins Above Replacement.
- [ ] chapters/bigdata/applications/sport.md:44:### Wins Above Replacement
- [ ] chapters/bigdata/applications/sport.md:46:Wins above Replacement WAR, Discussion of Calculation, Examples,
- [ ] chapters/bigdata/applications/sport.md:50:[:clapper: Wins Above Replacement
- [ ] chapters/bigdata/applications/sport.md:149:-   <http://en.wikipedia.org/wiki/Wins_Above_Replacement> [@www-wiki-wins-above-replacement]
- [ ] chapters/bigdata/applications/cloud.md:170:Before too much excitement sets in, note that spinach is above clouds
- [ ] chapters/deprecated/fall2017.md:194:             Above class open to graduate engineering students only
- [ ] chapters/deprecated/fall2017.md:195:             Above class taught online
- [ ] chapters/deprecated/fall2017.md:198:          Above class meets in the Smith Research Center, 151E
- [ ] chapters/deprecated/fall2017.md:204:             Above class open to graduates only
- [ ] chapters/deprecated/fall2017.md:205:             Above class taught online
- [ ] chapters/deprecated/fall2017.md:208:             Above class meets with INFO-I 423
- [ ] chapters/deprecated/fall2017.md:219:             Above class for students not in residence on the Bloomington
- [ ] chapters/deprecated/fall2017.md:226:             Above class open to undergraduates only
- [ ] chapters/deprecated/fall2017.md:227:             Above class taught online
- [ ] chapters/deprecated/fall2017.md:230:             Above class meets with INFO-I 523

"below"
---
- [ ] chapters/prg/python/numpy/numpy.md:91:below that range will 'underflow' and wrap back around to the end.
- [ ] chapters/prg/python/scikit-learn/scikit-learn.md:250:Below, we create a function that allows us to create these features in a
- [ ] chapters/preface/issues.md:64:| 60 | 231 | [above, below][i231] | bfeng | internal |
- [ ] chapters/in/aws-elasticbeanstalk.md:81:An AWS account can be created using the link below
- [ ] chapters/in/aws-elasticbeanstalk.md:88:Login to the AWS account using the link below.
- [ ] chapters/in/aws-documentdb.md:75:An AWS account can be created using the link below
- [ ] chapters/in/aws-documentdb.md:81:Login to the AWS account using the link below.
- [ ] chapters/in/aws-auroradb.md:92:An AWS account can be create using the link below
- [ ] chapters/in/aws-auroradb.md:98:Login to the AWS account using the link below.
- [ ] chapters/in/aws-auroradb.md:392:Once the python package is installed, the below python script can be used to connect to
- [ ] chapters/faas/openlambda.md:18:OpenLambda source code it available on github (all material below have been sourced from github): <https://github.com/open-lambda/open-lambda>.
- [ ] chapters/faas/openlambda.md:50:More details on this tool can be found [below](#admin-tool).
- [ ] chapters/faas/openlambda.md:153:The layout of these files in the <ROOT> directory is described in detail below.
- [ ] chapters/faq-516.md:70:notation.md file of the lecture notes Do not use the words below and
- [ ] chapters/faq-516.md:71:above, as the images can float and below and above makes ABSOLUTELY NO
- [ ] chapters/faq-516.md:209:I was interested in adding the following item below to the book in the data center section "6.4 Data Center Characteristics" as another bullet example of AWS failures that have occurred:
- [ ] chapters/ai/ai.md:48:sign based on being above or below the median. In k-NN predictions are
- [ ] chapters/doc/report.md:151:13. Have you not used phrases such as shown in the Figure below, but
- [ ] chapters/doc/report-2.md:190:13. Have you not used phrases such as shown in the Figure below, but
- [ ] chapters/doc/report-book-2.md:312:-   Do not use phrases such as *shown in the Figure below*. Instead, use
- [ ] chapters/doc/report-book-2.md:401:-   Do not artificially inflate your paper if you are below the page
- [ ] chapters/doc/writing-markdown.md:310:1.  Do not artificially inflate your paper if you are below the page
- [ ] chapters/arch.md:55:Some key attributes of MainFrames can be found in the following article (https://itstillworks.com/characteristics-of-a-mainframe-computer-10270.html)as well as are mentioned below:
- [ ] chapters/mapreduce/amazon-emr-2.md:92:drop-down menu, as in figure @fig:security. Below that you can then select which permissions model

**Comment by laszewsk** [comment]
i marked some issues that do not nee dto be fixed
